### ISSUE TITLE
Stuck forever on "Waiting for another download"

### ISSUE THREAD

**Issue by SeAlgoAsoma** [kitematic/kitematic#1099]
Latest version, running on OS X 10.10. Is every docker tool for OS X broken?

Never mind, it just coughed up more error messages than I care to spend my evening typing for you. No such container, connection refused, a whole bunch of errors. Now it won't let me delete my partially downloaded container. This thing appears to be very far from usable software, I'm done. You guys should at least get it *mostly* working before you call it "beta" and distribute it, so you're not wasting the publics time with software that's not even close to usable.

**Comment by FrenchBen** [comment]
@SeAlgoAsoma As with any Beta software and different environment setups issues do happen and why this section exists. Kitematic has been working really well for me for a while and each update fixes some of the bugs found via issues encountered by other users.

Did you search the list of issues for a possible similar problem and possible fixes? We have a wiki that also highlights some of the solutions that allowed other users to get their docker tool setup working as expected: https://github.com/kitematic/kitematic/wiki/Common-Issues-and-Fixes

If you're willing to help us debug your issue, it would be appreciated. I would need to know the following:
* Kitematic version: You can go to the menu and click on 'About' and screenshot it
* What image were you trying to download?
* Were you logged in to the DockerHub when doing it?
* If you were logged in, did you validate your email address?

**Comment by mchiang0610** [comment]
Sorry about that @SeAlgoAsoma It seems like Docker Hub was performing a maintenance. Kitematic is still in beta.

**Comment by neotrek** [comment]
Still encountering this problem, I serious feel your guys should reopen this.
In order to eliminate some probable external problem, I initiated download for another repo, and it went well. Meanwhile, wherever those repos got stuck, they do not got out. 
Docker Kitematic 0.8.7 built with engine 1.8.3, machine 0.4.1 running on OS X.
I think it's some UI problem or whatsoever, nah, not able to determine.

**Comment by FrenchBen** [comment]
@neotrek It's usually not a UI issue, but rather a VM connectivity issue. All downloads happen within your VM (named default), when the download doesn't start or gets stuck, it's usually because the virtualbox network daemon lost connectivity. 
If you look through the changelogs (https://www.virtualbox.org/wiki/Changelog) you'll see that keeping the network healthy has always been part of each release.
