### ISSUE TITLE
Tag latest not found in repository docker.io/yogasmahajan/yogasmahajan

### ISSUE THREAD

**Issue by Yogiraj24** [kitematic/kitematic#1102]
Tag latest not found in repository docker.io/yogasmahajan/yogasmahaj

Unable to connect the Dokcer Hub via Kitematic

**Comment by FrenchBen** [comment]
@Yogiraj24 If you look at the image repository you will notice that no 'tags' actually exist for that image. I would suggest creating a tag in order to download it - The 'latest' tag is the default and why there is an attempt made at downloading it:
https://hub.docker.com/r/yogasmahajan/yogasmahajan/tags/
