### ISSUE TITLE
ETIMEDOUT when trying to start sleepy_brattain container from Kitematic

### ISSUE THREAD

**Issue by robnardo** [kitematic/kitematic#1149]
im using Windows 8 and after executing "docker run nginx" for the first time, i see that there more containers in the kitematic app (left column).  i tried opening sleepy_brattain and got this error

**Comment by FrenchBen** [comment]
This is somewhat the expected behavior - The docker run command you've pointed out doesn't name the container or specify how it should run - See the hub documentation for the proper flags:
https://hub.docker.com/_/nginx/

Instead of the command line, use kitematic directly to get your containers created. There's an official 'hello-world-nginx' image that you can spin up to see the proper behavior.

**Comment by FrenchBen** [comment]
Closing as this isn't really an issue but confusion on usage. Feel free to re-open if needed.
