### ISSUE TITLE
ptxdist:latest is missing, can not pull

### ISSUE THREAD

**Issue by omegasteffy** [kitematic/kitematic#1237]

**Comment by mikaoelitiana** [comment]
I think the problem is that kitematic would download tag latest by default and doesn't check if this tag exists or not. 
To download it, you can switch the tag before downloading the container : 

![capture d ecran 2015-11-23 a 09 23 56](https://cloud.githubusercontent.com/assets/674667/11330895/043b96ec-91c4-11e5-9a45-af1cd3d6d9ac.png)

**Comment by FrenchBen** [comment]
@mikaoelitiana is correct - Please make sure that the tag exists before using it.
