### ISSUE TITLE
Are there any way to import current images and container already created with boot2docker?

### ISSUE THREAD

**Issue by artefactop** [kitematic/kitematic#162]

**Comment by mk101** [comment]
They should be reflected on Kitematic automatically. Are you not seeing them?

**Comment by artefactop** [comment]
No they don't, check it

![screen shot 2015-01-28 at 14 28 56](https://cloud.githubusercontent.com/assets/1199371/5938325/1b8d9dbe-a6fa-11e4-913a-2f9225ee4481.png)

**Comment by jeffdm** [comment]
Right now we don't show containers without exposed ports.

For CLI containers without ports (like `hello-world`), this is more or less a bug. As of Kitematic 0.5 that will be changed - all containers run from a tagged image (pretty much any container you'd ever want to see will be shown). 

Thanks for the issue!

**Comment by jeffdm** [comment]
This was fixed in 0.5. Anything done on CLI is reflected in Kitematic now :smile:

Note that 0.5 now uses [machine](https://github.com/docker/machine). We even have a little terminal button in the bottom-left of the app you can use to open a docker-ready terminal on your mac. 

That said, you can't directly important from a boot2docker vm yet via machine, there's a ticket open for that IIRC. Look out for this soon!

Jeff
