### ISSUE TITLE
500 server error - No command specified

### ISSUE THREAD

**Issue by avolve** [kitematic/kitematic#429]
Hi everyone,

Hoping you can help/point me in the right direction to resolve a '500 server error - No command specified' when trying to download a Discourse container.

I have tried on two different MacBook Pros running Yosemite, with fresh installs of Kinematic (one with Virtual box installed previously, one without).

Appreciate any advice
avolve.

**Comment by jeffdm** [comment]
@avolve thanks for the issue.

This is a duplicate of #230, and should have definitely been fixed by now. Sorry about that.

The reason it occurs is because Discourse's Dockerfile does not have a `CMD` directive telling Kitematic how to run it.

Will get to this as soon as I can, or feel free to try at a fix :smiley:

**Comment by jeffdm** [comment]
Going to close since it's a dupe, but keep an eye on #230
