### ISSUE TITLE
500 server error if CMD is not specified in the Dockerfile

### ISSUE THREAD

**Issue by xalapa** [kitematic/kitematic#436]
when I try to install docker-cyanogenmod I got the error "500 server error - No command specified" during the installation process

**Comment by TeckniX** [comment]
This is due to an incorrect/custom Dockerfile - When a docker container is created/started, a  command is usually specified to ensure that the container starts up with the proper service/command.

Most of the stuff it's bash, but it can also be a service like httpd, redis, etc. 

The problem with the image that you chose, is that the maintainer create a custom script to do, which is not within docker convention. The script should be part of the Dockerfile and then called with a command such as: sh /run.sh

Maybe in the future we can allow users to pass their own command for creation, right now it's not implemented.

**Comment by jeffdm** [comment]
@TeckniX thanks for the reply! Right - Kitematic requires a CMD directive in the Dockerfile of the image you're trying to run.

**Comment by nickbroon** [comment]
Can this be re-opened and mark as with the enhancement label to track what would be a very useful feature? I've come across quite a view development dockerfiles that don't contain a command.
