### ISSUE TITLE
Error while setting up jenkins container, no error reason mentioned.

### ISSUE THREAD

**Issue by basavaraj1985** [kitematic/kitematic#511]
While trying to setup jenkins container through Kitematic Beta ( Version 0.5.25 ), "An error occurred: -" is displayed. 

Environment details:
OS X Version 10.9.5

![screen shot 2015-05-18 at 11 47 46 am](https://cloud.githubusercontent.com/assets/1935324/7675249/c1a2f6f4-fd53-11e4-9016-3392eb1b58f0.png)

**Comment by basavaraj1985** [comment]
Actually, its the same error for any container I try to setup.

**Comment by mchiang0610** [comment]
@basavaraj1985 It's most likely due to Kitematic unable to connect to the VM. 

Can you open VirtualBox and remove the VM called "dev". (Do note, if you have previously been working on Docker machine, it will remove the data). 

Once that is done, restart Kitematic. 

Going to close this for now. Please re-open if it doesn't work.
