### ISSUE TITLE
Hub connection doesn't work when having a proxy with authentication

### ISSUE THREAD

**Issue by ilaborie** [kitematic/kitematic#562]

**Comment by mchiang0610** [comment]
@ilaborie Thanks for reporting - this is an issue around proxies with Docker-machine.

**Comment by ahalem** [comment]
any luck fixing this bug ?

**Comment by mchiang0610** [comment]
@ahalem We're still having problem with this issue. It's not an isolated issue with Kitematic as we use docker-machine under the hood. 

Are you running into this problem? If so, would it be possible to give us logs to troubleshoot further?

**Comment by ahalem** [comment]
Is Kitematic and Docker Machine connecting to IP or domain name  when connecting to the Docker Hub, would you please provide me the value for this IP or domain name ? I might be able to consult some network Engineer here, I got similar issue with Open VPN before.


———————————————————————
Amr Abdelhalem
Principal Architect - Application Tier Engineering
ADP, LLC – Roseland, NJ | Office:  973-974-7143  - Application Tier 24/7 Support Hotline: 1-855-848-3895
“Creativity is just connecting things. When you ask creative people, they feel a little guilty because they didn't really do it, they just saw something”  - Steve Jobs

**Comment by mchiang0610** [comment]
#1031 Merging with

**Comment by mchiang0610** [comment]
If anyone still has problems with this on Mac or Windows 10+, please contact me at mchiang@docker.com.

We are working on something to help address this issue.
