### ISSUE TITLE
[bug] Kitematic makes plaintext HTTP requests to api.mixpanel.com and kitematic.com

### ISSUE THREAD

**Issue by bgentry** [kitematic/kitematic#709]
First time using Kitematic, and my firewall tells me it's making plaintext HTTP requests to api.mixpanel.com and kitematic.com.

Is there any reason it shouldn't be using HTTPS for everything?

**Comment by bgentry** [comment]
@mchiang0610 @jeffdm thanks! but it looks like that doesn't fix MixPanel over port 80. Can that be fixed too?

**Comment by jeffdm** [comment]
@bgentry thanks for the issue. Sorry - I think GitHub auto closed this, reponing.

For mixpanel, Mixpanel's official node library forces http, but this needs to be changed immediately. Note that no sensitive data is included in Kitematic's mixpanel metrics - only anonymous actions like `container created` but not which image it was from.

For the requests to Kitematic.com, this was just fixed in #710. The only requests over http are for the images in the browse section. Inline scripts are disabled and these images are the same for anyone. On an initial look this posed no immediate risk

I will cut a new release once both are fixed

**Comment by bgentry** [comment]
@jeffdm thanks for the prompt responses and being on top of this :v: :lock:

**Comment by jeffdm** [comment]
@bgentry ok fixed the mixpanel part in #711 

Closing for now - but always feel free to reopen this Thanks so much for spotting this.
