### ISSUE TITLE
Kitematic 0.7.4 on Win8.1 stucks at 99%....again

### ISSUE THREAD

**Issue by percoclap** [kitematic/kitematic#727]
Hi all

I just installed 0.7.4 on fresh win8.1 x64 (no previous docker or virtualbox installed), no anti virus or firewall
It installs virtual box / create the VM "kitematic" but stucks at 99%....nothing happens

I tried to reboot and click on kitematic desktop icon, it initializes then same thing, block at 99%

Do you know how to fix it? what is the trick? thanks for your help!!

**Comment by percoclap** [comment]
oh and ten minutes after I got the message: "Sorry! machine IP could not be fetched. Please retry the setup  "....Any idea?

**Comment by r4j4h** [comment]
I am getting the same, no resolution so far :( I had boot2docker installed prior. If there is any incompatibility there you should probably document it on the README in big highlighter considering this is included in the Docker mailing list, et al..

**Comment by r4j4h** [comment]
So I resolved this issue for my machine thanks to [this thread](http://superuser.com/questions/791901/why-vt-x-support-is-disabled)!

The culprit was Hyper-V was enabled in my Windows from Visual Studio's Phone SDK. After I disabled that I re-ran Kitematic which ran through to 99% and failed. I hit the `Delete VM and Retry` button and lo and behold it went through fine. :)

**Comment by jeffdm** [comment]
Thanks @r4j4h ! Closing this in favor of #386
