### ISSUE TITLE
Please make the submission of app statistics opt-out/opt-in

### ISSUE THREAD

**Issue by runasand** [kitematic/kitematic#784]
According to [the FAQ](https://kitematic.com/docs/faq/), Kitematic tracks how users are interacting with the app. Even though you are not collecting sensitive information, I would still like to see the submission of this information be opt-out/opt-in.

**Comment by jeffdm** [comment]
@runasand you can disable tracking in the Preferences pane in-app :)!

Thanks for the issue - I'll close this for now but feel free to re-open

**Comment by pmario** [comment]
Hi @jeffdm 
I'm having closer look to kitematic source atm and I think this issue should be reopened. 

Docker Toolbox install dialog asks the user if feedback is allowed. .. Having a fast look at the toolkit install code, it seems this info is only used by the installer and not by the installed programs. ....

As far as I can see in the Kitematic source, the program sends information to a 3rd party service, at the program startup / setup procedure. .. For me that's definitely a problem. .. It's too late, if the user can decide to opt out, after information is already sent. 

I'm replying to the closed issue, since I'm not 100% sure yet. I want to use Kitematic with hyper-v. So I'm not able at the moment to create the exact workflow. 

But having a look at [this video from Wednesday on youtube](https://www.youtube.com/watch?v=dwMcmfZaA6Q) for me it seems, opting out is not possible, after information is sent already. 

If I'm right, please reopen the issue.
