### ISSUE TITLE
Kitematic does not start instantly when the VM is already up

### ISSUE THREAD

**Issue by nathanleclaire** [kitematic/kitematic#852]
When I start Kitematic from scratch with `dev` already running I am greeted by a blank screen and then a progress bar indicating that the VM is being started.  It's already running though ;D  This makes the process of booting Kitematic take 10-15 seconds and I feel like ideally it should start up almost instantaneously (assuming the VM is already running).

Take a look at the recently merged `docker-machine status` command which might help out a bit here.

**Comment by jeffdm** [comment]
Thanks for the issue!

**Comment by nathanleclaire** [comment]
![](http://dirkkelly.com/gifs/chuck-norris/chuck-norris.gif)

**Comment by nathanleclaire** [comment]
Is this fixed?

**Comment by mchiang0610** [comment]
oops. Closed this wrong.

**Comment by lemonkoala** [comment]
I think I have the same problem where dev is already running and is the only host I have.
When starting Kitematic, it does take 10-15 seconds because it creates a default host and then uses that. It ignores my already running dev host. That means I am greeted with an empty container list.

Is there a way for me to force Kitematic to use my already running dev host?

**Comment by FrenchBen** [comment]
@lemonkoala The latest Kitematic will look for a VM labelled `default` - The above issue has also been fixed; once the `default` VM is up and running then the startup should be close to instant.

**Comment by nathanleclaire** [comment]
:+1:
