### ISSUE TITLE
Expose public hosts and ports as ENV variables

### ISSUE THREAD

**Issue by simoami** [kitematic/kitematic#879]
When a container is linked to another container, its environment variables are shared, which is great. However, I'm wondering what's the usefulness of exposing container ports if they cannot be used from by containers, when they are different from the random public ports. This forces us to manually reinsert these every time, which is not practical.

It would help a lot if the public hosts and ports generated with docker run  `-P` option are made available as environment variables, just like you see in PaaS cloud platforms.

**Comment by FrenchBen** [comment]
I'm not sure if I understand the issue - All connection/port details are made accessible during the linking process, within the container as ENV vars. Do you have an example of your use-case and issues encountered?

**Comment by simoami** [comment]
Yes, unfortunately not the public host and port, just the internal ones:

![katematic-env](https://cloud.githubusercontent.com/assets/2038264/9012719/2113aac8-3785-11e5-98ec-fb44352ce83e.png)

And here's the list of exposed environment variables. none of the redis ones contain host 192.168.99.100 or port 32772:

```sh
bash-3.2$ docker run -i -t --rm -P -v `pwd`:/src --link redis om/vendors sh
# env
REDIS_PORT=6379
MQLIGHT_PORT=5672
REDIS_PORT_6379_TCP_ADDR=172.17.0.2
HOSTNAME=d59eef7e6259
REDIS_NAME=/sharp_cray/redis
REDIS_PORT_6379_TCP_PORT=6379
HOME=/root
REDIS_PORT_6379_TCP_PROTO=tcp
REDIS_ENV_REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-3.0.3.tar.gz
REDIS_ENV_REDIS_VERSION=3.0.3
REDIS_PORT_6379_TCP=tcp://172.17.0.2:6379
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
REDIS_HOST=localhost
PWD=/src
REDIS_ENV_REDIS_DOWNLOAD_SHA1=0e2d7707327986ae652df717059354b358b83358
MQLIGHT_HOST=mqlight
NODE_ENV=production
```

**Comment by FrenchBen** [comment]
@simoami You're missing out on the magic ;)

Your Redis Host is connected within the container-  So instead of connecting to it via the 192.168.... you just use `ENV['REDIS_PORT_6379_TCP_ADDR']` as the host and `ENV['REDIS_PORT_6379_TCP_PORT']` as the port in your code. You can also see that the full string is set here: `ENV['REDIS_PORT_6379_TCP']`

If you look at the /etc/hosts file, you'll see that there's even a host entry for the Redis server and it's associated with the proper IP in there. 
The `192.168....` Ip is only if you wanted to connect to it from outside of a container.

**Comment by simoami** [comment]
@FrenchBen That makes sense. I guess I got confused from running some microservices outside of the vm host for debugging purposes. Thanks for clarifying.

**Comment by FrenchBen** [comment]
no pb :+1:  - Can you close this issue if it's been resolved?

**Comment by simoami** [comment]
right away!
