### ISSUE TITLE
Shutting down VM to be able update VirtualBox 

### ISSUE THREAD

**Issue by iBobik** [kitematic/kitematic#903]
I tried to update VirtualBox, but installer told me there is running VM. So I turned off Kitematic and ... it did not worked again. So I opened Kitematic and checked how to turn off the machine. Nothing found, but there is option to turn off machine while quiting Kitematic (by default unchecked, strange). Not exacly what I wanted, but it should work. So I turned off Kitematic again and immediately started VirtualBox installator. Again it told me there is running VM. Hmm, maybe it taked a while to turn off VM, but why Kitematic did not did not showed me some feedback to know when it will be turned off? After about one minute of waiting it was possible to run installation.

So to have Kitematic more user friendly I recommend:
- Add option to turn on and off VM from GUI (to menu? some green/red icon with menu?)
- Not block GUI while starting VM. Why I can not prepare config, browse directory etc. while the VM "lazy loads" at background (with some indicator in red/green icon)?
- Have Shut down VM on closing Kitematic option turned on by default
- Not close GUI immediately after user want, but give user feedback that VM is turning off and close window than. (Maybe with simillar progress bar what is currently on start.)

**Comment by FrenchBen** [comment]
@iBobik If you look in the wiki, you'll see that a lot of this is document in the up-coming machine changes:
https://github.com/kitematic/kitematic/wiki/Machine-Management

If you use Kitematic a lot, it's actually nice to open it with the VM already running or close it and keep working with your containers without Kitematic open (aka VM still running)

**Comment by iBobik** [comment]
I am talking about UI changes to improve usability, mainly for new users.
And this is not there.



Jan Pobořil

2015-08-11 0:26 GMT+02:00 FrenchBen <notifications@github.com>:

**Comment by FrenchBen** [comment]
Although perhaps not clear, the wiki does in fact talk about UI changes as you mentioned, where the VM status would be shown and allow you to start/stop it.

Unfortunately until the VM is up and running there isn't much you can do, as it's the main repository for all of your containers.

**Comment by mchiang0610** [comment]
Hi @iBobik  Thank you so much for this. 

1. Add option to turn on and off VM from GUI (to menu? some green/red icon with menu?)
In Kitematic settings you will be able to do this from GUI for when closing Kitematic. We don't yet have a display on your VM status. 

2. Not block GUI while starting VM. Why I can not prepare config, browse directory etc. while the VM "lazy loads" at background (with some indicator in red/green icon)?
The reason for blocking Kitematic while starting VM is because almost every action you will need to do requires the VM. (except browsing of course, but that's not most of our users' behavior). Kitematic at the start, checks and starts the VM. 

3. Have Shut down VM on closing Kitematic option turned on by default
Thanks for this suggestion. 

4. Not close GUI immediately after user want, but give user feedback that VM is turning off and close window than. (Maybe with simillar progress bar what is currently on start.)
The GUI can be closed immediately.
