### ISSUE TITLE
Cannot kill container jenkins: Container 

### ISSUE THREAD

**Issue by unbug** [kitematic/kitematic#994]
```sh
server error
500
Cannot kill container jenkins: Container e5d1ed9d8ddc118114ba0085ea1273a220e1a8234c1e4bc83656c8ea50eb097d is not running
```

How can I remove a jenkins container?

**Comment by FrenchBen** [comment]
I was able to download and delete the container without any issues - Can you quit Kitematic and re-open it to try this again?

**Comment by unbug** [comment]
yeah,I tried,I even restart my mac and create another container.all the same issue,no lucky.

**Comment by FrenchBen** [comment]
Can you provide the output of the following commands:
`docker-machine ssh default` - Will get you in the VM
`docker ps -a` - Will list all available containers
`docker images` - will list all downloaded images

**Comment by unbug** [comment]
```sh
unbug@unbug-mbp.local:~$ docker-machine ssh default
FATA[0000] Host does not exist                          
unbug@unbug-mbp.local:~$ docker ps -a
FATA[0000] Get http:///var/run/docker.sock/v1.18/containers/json?all=1: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
unbug@unbug-mbp.local:~$ docker images
FATA[0000] Get http:///var/run/docker.sock/v1.18/images/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by FrenchBen** [comment]
@unbug Seems you're working with an older version of kitematic - Can you share the version?
For now can you list your existing machines?
`docker-machine ls`

**Comment by unbug** [comment]
Version 0.7.6
```sh
unbug@unbug-mbp.local:~$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL   SWARM
dev    *        virtualbox   Stopped    
```

**Comment by FrenchBen** [comment]
I should've asked for the software version first. 
The above commands have been updated to reflect your VM settings:
`docker-machine start dev` - Will start your VM
`docker-machine ssh dev` - Will get you in the VM
`docker ps -a` - Will list all available containers
`docker images` - will list all downloaded images
When done, you can exit the VM with a simple `exit` command.

If this is all for your Dev setup, I would suggest updating to the latest [Docker toolbox](https://www.docker.com/toolbox)

**Comment by unbug** [comment]
thanks ;)

**Comment by funkytaco** [comment]
I'm running into this problem as well. I'm having to ssh to `dev` to delete the images (which is then reflected in kitematic).


I tried this:

brew upgrade docker
brew upgrade docker-machine
docker-machine upgrade dev

For the last one, I got this:

docker-machine upgrade dev

Stopping machine to do the upgrade...

exit status 1
I had to reboot my laptop before I was able to upgrade.


What else do i need to upgrade?

**Comment by FrenchBen** [comment]
@funkytaco I would use the [Docker Toolbox](https://www.docker.com/toolbox) instead of brew, as it will update everything for you.

**Comment by funkytaco** [comment]
@FrenchBen, I decided to move to Docker Toolbox as you suggested. It looks like homebrew had some duplicate tools. I'm putting this here for anyone curious.

    $ brew uninstall docker
    Uninstalling /usr/local/Cellar/docker/1.8.1... (9 files, 8.9M)
    docker 1.7.1 is still installed.
    Remove them all with `brew uninstall --force docker`.

    $ brew uninstall docker
    Uninstalling /usr/local/Cellar/docker/1.7.1... (9 files, 7.4M)

    $ brew uninstall docker-machine
    Uninstalling /usr/local/Cellar/docker-machine/0.4.1... (5 files, 16M)
    docker-machine 0.3.1 is still installed.
    Remove them all with `brew uninstall --force docker-machine`.

    $ brew uninstall docker-machine
    Uninstalling /usr/local/Cellar/docker-machine/0.3.1... (5 files, 16M)

    $ brew uninstall docker-compose
    Uninstalling /usr/local/Cellar/fig/1.4.0... (374 files, 4.6M)


I then installed Docker Toolbox 1.8.1c

The biggest catch here is there is now a docker host named `default` and my old one is called `dev`,
so Kitematic 0.8.3 was still looking at the wrong Docker host.

    $ docker-machine ls
    NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
    default            virtualbox   Running   tcp://192.168.99.101:2376   
    dev       *        virtualbox   Running   tcp://192.168.99.100:2376


I created [this](https://gist.github.com/funkytaco/db49142cf84b741bd9ed) cleanup script to remove all of my containers since I didn't need them. I'm wondering if there is a way I could have migrated them if I wanted to?

I also updated my rc file (for my OSX shell) to point to the new "default" docker host to set up the local environment variables:

`eval "$(docker-machine env default)"
`

Until I update the eval, they were still spinning up in my old `dev` host. 

So then I destroyed my old Docker host with this:

`$docker-machine rm dev `

**Comment by FrenchBen** [comment]
@funkytaco Thank you for the great walk-through on getting things cleaned up.
Getting a migration of containers wouldn't be impossible as we already have it for the old boot2docker - Thankfully you didn't need the containers, but it can otherwise be an issues.

As a side note, if you were to remove the VM to begin with, then you could've done just that and all container/images would've been removed too with it.
